language: node_js
dist: xenial
node_js:
  - "10.16.0"
sudo: false

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

cache:
  directories:
    - ./node_modules

install:
  - npm install

branches:
  only:
  - master

before_script:
  # Install commitlint cli for travis
  - npm install @commitlint/travis-cli

script:
  # Lint the commit messages
  - commitlint-travis
  - ng lint
  - ng build components
  - ng test components --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
  - ng build --prod --baseHref=https://prosoft-edv.github.io/components/

notifications:
  email:
    on_failure: change
    on_success: change

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/prosoft-components-demo
  on:
    branch: master
