name: pull request ci

on: [pull_request]

jobs:
  commitlint:
    name: commit lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v3

  codelint:
    name: code lint
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '15'
    - name: lint
      run: |
        npm ci
        npm run ng -- lint
      env:
        CI: true

  test:
    name: test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '15'
    - name: test
      run: |
        npm ci
        npm run ng -- test components --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
        npm run test:schematics
      env:
        CI: true

  build:
    name: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '15'
    - name: build
      run: |
        npm ci
        npm run build:components
        npm run ng -- build --prod --baseHref=https://prosoft-edv.github.io/components/
      env:
        CI: true
